name: Build

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          submodules: recursive

      - name: Run Base Pifile
        uses: Nature40/pimod@v0.5.0
        with:
          pifile: Base-Nano-2GB.Pifile
      - name: Run BirdAtEdge Pifile
        uses: Nature40/pimod@v0.5.0
        with:
          pifile: BirdAtEdge-Nano-2GB.Pifile

      - name: Set Release Version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Rename BirdAtEdge Image
        run: mv BirdAtEdge-Nano-2GB.img BirdAtEdge-Nano-2GB-${{ env.RELEASE_VERSION }}.img
      - name: Package BirdAtEdge.zip
        run: zip BirdAtEdge-Nano-2GB-${{ env.RELEASE_VERSION }}.zip BirdAtEdge-Nano-2GB-${{ env.RELEASE_VERSION }}.img
      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: true
      - name: Upload BirdAtEdge.zip to release
        id: upload_BirdAtEdge_zip
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: BirdAtEdge-Nano-2GB-${{ env.RELEASE_VERSION }}.zip
          asset_name: BirdAtEdge-Nano-2GB-${{ env.RELEASE_VERSION }}.zip
          asset_content_type: application/zip
